//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdgeExpressDemoPOS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Globals : global::System.Configuration.ApplicationSettingsBase {
        
        private static Globals defaultInstance = ((Globals)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Globals())));
        
        public static Globals Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800000001844")]
        public string XWebID {
            get {
                return ((string)(this["XWebID"]));
            }
            set {
                this["XWebID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80023396")]
        public string XWebTerminalID {
            get {
                return ((string)(this["XWebTerminalID"]));
            }
            set {
                this["XWebTerminalID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WFiNd0nMIsejrWVUSycsmbtgkMN7hELK")]
        public string XWebAuthKey {
            get {
                return ((string)(this["XWebAuthKey"]));
            }
            set {
                this["XWebAuthKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Derek")]
        public string ClerkID {
            get {
                return ((string)(this["ClerkID"]));
            }
            set {
                this["ClerkID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TransactionCounter {
            get {
                return ((int)(this["TransactionCounter"]));
            }
            set {
                this["TransactionCounter"] = value;
            }
        }
    }
}
