//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeveloperServicesPOS.PABDemo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class PABDemo : global::System.Configuration.ApplicationSettingsBase {
        
        private static PABDemo defaultInstance = ((PABDemo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PABDemo())));
        
        public static PABDemo Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string CCProcessingEnabled {
            get {
                return ((string)(this["CCProcessingEnabled"]));
            }
            set {
                this["CCProcessingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://staging.agreementexpress.net/api/TemplateServices/v2/publishTransaction?a" +
            "gexp_transrefid=LP_Test&agexp_transfolderid=1748&agexp_transcompany=645&allRecip" +
            "ients=Owner1:Owner1&aex_direct=true")]
        public string RapidActivateURL {
            get {
                return ((string)(this["RapidActivateURL"]));
            }
            set {
                this["RapidActivateURL"] = value;
            }
        }
    }
}
