//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEHP_Tester {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Globals : global::System.Configuration.ApplicationSettingsBase {
        
        private static Globals defaultInstance = ((Globals)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Globals())));
        
        public static Globals Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C9CBE35FCE67540F328FE4FC8758AF6DCECC24954FB2C4FFE4A24F2B81D95FEA9953BC5CF45601D07" +
            "8")]
        public string AccountToken {
            get {
                return ((string)(this["AccountToken"]));
            }
            set {
                this["AccountToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C9CBE35FCE67540F328FE4FC8758AF6DCECC24954FB2C4FFE4A24F2B81D95FEA9953BC5CF45601D07" +
            "8")]
        public string DefaultAccountToken {
            get {
                return ((string)(this["DefaultAccountToken"]));
            }
            set {
                this["DefaultAccountToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3C6D0A90CE65590E308DEDFC8657AC62CDCF2B9E43B2CAFEEDA34B258CDE5FEA9B51BE5C8A78F86FF" +
            "C")]
        public string LoopBackAccountToken {
            get {
                return ((string)(this["LoopBackAccountToken"]));
            }
            set {
                this["LoopBackAccountToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("301B206BCE6D570C378EEEFB8D59AD60CFCB2D9542B1C4FFEBA9402185DE5FEA9953BE585C8E0F121" +
            "D")]
        public string CanadianAccountToken {
            get {
                return ((string)(this["CanadianAccountToken"]));
            }
            set {
                this["CanadianAccountToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Querystring")]
        public string QueryResponseMode {
            get {
                return ((string)(this["QueryResponseMode"]));
            }
            set {
                this["QueryResponseMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test")]
        public string ProcessingMode {
            get {
                return ((string)(this["ProcessingMode"]));
            }
            set {
                this["ProcessingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PayPage Post")]
        public string SubmitMethod {
            get {
                return ((string)(this["SubmitMethod"]));
            }
            set {
                this["SubmitMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomParameters {
            get {
                return ((string)(this["CustomParameters"]));
            }
            set {
                this["CustomParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PostParameters {
            get {
                return ((string)(this["PostParameters"]));
            }
            set {
                this["PostParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QueryResponse {
            get {
                return ((string)(this["QueryResponse"]));
            }
            set {
                this["QueryResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCMStatus {
            get {
                return ((string)(this["RCMStatus"]));
            }
            set {
                this["RCMStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Amount {
            get {
                return ((string)(this["Amount"]));
            }
            set {
                this["Amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OrderID {
            get {
                return ((string)(this["OrderID"]));
            }
            set {
                this["OrderID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QueryParameters {
            get {
                return ((string)(this["QueryParameters"]));
            }
            set {
                this["QueryParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DuplicateOn {
            get {
                return ((string)(this["DuplicateOn"]));
            }
            set {
                this["DuplicateOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DuplicateOff {
            get {
                return ((string)(this["DuplicateOff"]));
            }
            set {
                this["DuplicateOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.openedgedeveloper.com")]
        public string DevPortalURL {
            get {
                return ((string)(this["DevPortalURL"]));
            }
            set {
                this["DevPortalURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeveloperServices@openedgepay.com")]
        public string ContactDevServices {
            get {
                return ((string)(this["ContactDevServices"]));
            }
            set {
                this["ContactDevServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OneButton")]
        public string SubmitMode {
            get {
                return ((string)(this["SubmitMode"]));
            }
            set {
                this["SubmitMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SessionToken {
            get {
                return ((string)(this["SessionToken"]));
            }
            set {
                this["SessionToken"] = value;
            }
        }
    }
}
