//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEHP_Tester {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class PayPageCosmetic : global::System.Configuration.ApplicationSettingsBase {
        
        private static PayPageCosmetic defaultInstance = ((PayPageCosmetic)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PayPageCosmetic())));
        
        public static PayPageCosmetic Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bill_customer_title_label {
            get {
                return ((string)(this["bill_customer_title_label"]));
            }
            set {
                this["bill_customer_title_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bill_customer_title_visible {
            get {
                return ((bool)(this["bill_customer_title_visible"]));
            }
            set {
                this["bill_customer_title_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bill_customer_title_edit {
            get {
                return ((bool)(this["bill_customer_title_edit"]));
            }
            set {
                this["bill_customer_title_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_customer_title_mandatory {
            get {
                return ((bool)(this["bill_customer_title_mandatory"]));
            }
            set {
                this["bill_customer_title_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bill_first_name_label {
            get {
                return ((string)(this["bill_first_name_label"]));
            }
            set {
                this["bill_first_name_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_first_name_visible {
            get {
                return ((bool)(this["bill_first_name_visible"]));
            }
            set {
                this["bill_first_name_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_first_name_edit {
            get {
                return ((bool)(this["bill_first_name_edit"]));
            }
            set {
                this["bill_first_name_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_first_name_mandatory {
            get {
                return ((bool)(this["bill_first_name_mandatory"]));
            }
            set {
                this["bill_first_name_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bill_company_label {
            get {
                return ((string)(this["bill_company_label"]));
            }
            set {
                this["bill_company_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_company_visible {
            get {
                return ((bool)(this["bill_company_visible"]));
            }
            set {
                this["bill_company_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_company_edit {
            get {
                return ((bool)(this["bill_company_edit"]));
            }
            set {
                this["bill_company_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_company_mandatory {
            get {
                return ((bool)(this["bill_company_mandatory"]));
            }
            set {
                this["bill_company_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bill_address_one_label {
            get {
                return ((string)(this["bill_address_one_label"]));
            }
            set {
                this["bill_address_one_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_address_one_visible {
            get {
                return ((bool)(this["bill_address_one_visible"]));
            }
            set {
                this["bill_address_one_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_address_one_edit {
            get {
                return ((bool)(this["bill_address_one_edit"]));
            }
            set {
                this["bill_address_one_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_address_one_mandatory {
            get {
                return ((bool)(this["bill_address_one_mandatory"]));
            }
            set {
                this["bill_address_one_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bill_address_two_label {
            get {
                return ((string)(this["bill_address_two_label"]));
            }
            set {
                this["bill_address_two_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_address_two_visible {
            get {
                return ((bool)(this["bill_address_two_visible"]));
            }
            set {
                this["bill_address_two_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_address_two_edit {
            get {
                return ((bool)(this["bill_address_two_edit"]));
            }
            set {
                this["bill_address_two_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_address_two_mandatory {
            get {
                return ((bool)(this["bill_address_two_mandatory"]));
            }
            set {
                this["bill_address_two_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bill_city_label {
            get {
                return ((string)(this["bill_city_label"]));
            }
            set {
                this["bill_city_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_city_visible {
            get {
                return ((bool)(this["bill_city_visible"]));
            }
            set {
                this["bill_city_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_city_edit {
            get {
                return ((bool)(this["bill_city_edit"]));
            }
            set {
                this["bill_city_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_city_mandatory {
            get {
                return ((bool)(this["bill_city_mandatory"]));
            }
            set {
                this["bill_city_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bill_state_or_province_label {
            get {
                return ((string)(this["bill_state_or_province_label"]));
            }
            set {
                this["bill_state_or_province_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_state_or_province_visible {
            get {
                return ((bool)(this["bill_state_or_province_visible"]));
            }
            set {
                this["bill_state_or_province_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_state_or_province_edit {
            get {
                return ((bool)(this["bill_state_or_province_edit"]));
            }
            set {
                this["bill_state_or_province_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_state_or_province_mandatory {
            get {
                return ((bool)(this["bill_state_or_province_mandatory"]));
            }
            set {
                this["bill_state_or_province_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bill_country_code_label {
            get {
                return ((string)(this["bill_country_code_label"]));
            }
            set {
                this["bill_country_code_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_country_code_visible {
            get {
                return ((bool)(this["bill_country_code_visible"]));
            }
            set {
                this["bill_country_code_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_country_code_edit {
            get {
                return ((bool)(this["bill_country_code_edit"]));
            }
            set {
                this["bill_country_code_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_country_code_mandatory {
            get {
                return ((bool)(this["bill_country_code_mandatory"]));
            }
            set {
                this["bill_country_code_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bill_postal_code_label {
            get {
                return ((string)(this["bill_postal_code_label"]));
            }
            set {
                this["bill_postal_code_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_postal_code_visible {
            get {
                return ((bool)(this["bill_postal_code_visible"]));
            }
            set {
                this["bill_postal_code_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_postal_code_edit {
            get {
                return ((bool)(this["bill_postal_code_edit"]));
            }
            set {
                this["bill_postal_code_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_postal_code_mandatory {
            get {
                return ((bool)(this["bill_postal_code_mandatory"]));
            }
            set {
                this["bill_postal_code_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string invoice_number_label {
            get {
                return ((string)(this["invoice_number_label"]));
            }
            set {
                this["invoice_number_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool invoice_number_visible {
            get {
                return ((bool)(this["invoice_number_visible"]));
            }
            set {
                this["invoice_number_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool invoice_number_edit {
            get {
                return ((bool)(this["invoice_number_edit"]));
            }
            set {
                this["invoice_number_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool invoice_number_mandatory {
            get {
                return ((bool)(this["invoice_number_mandatory"]));
            }
            set {
                this["invoice_number_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string purchase_order_number_label {
            get {
                return ((string)(this["purchase_order_number_label"]));
            }
            set {
                this["purchase_order_number_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool purchase_order_number_visible {
            get {
                return ((bool)(this["purchase_order_number_visible"]));
            }
            set {
                this["purchase_order_number_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool purchase_order_number_edit {
            get {
                return ((bool)(this["purchase_order_number_edit"]));
            }
            set {
                this["purchase_order_number_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool purchase_order_number_mandatory {
            get {
                return ((bool)(this["purchase_order_number_mandatory"]));
            }
            set {
                this["purchase_order_number_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string credit_card_verification_number_label {
            get {
                return ((string)(this["credit_card_verification_number_label"]));
            }
            set {
                this["credit_card_verification_number_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool credit_card_verification_number_visible {
            get {
                return ((bool)(this["credit_card_verification_number_visible"]));
            }
            set {
                this["credit_card_verification_number_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool credit_card_verification_number_edit {
            get {
                return ((bool)(this["credit_card_verification_number_edit"]));
            }
            set {
                this["credit_card_verification_number_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool credit_card_verification_number_mandatory {
            get {
                return ((bool)(this["credit_card_verification_number_mandatory"]));
            }
            set {
                this["credit_card_verification_number_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string order_information_label {
            get {
                return ((string)(this["order_information_label"]));
            }
            set {
                this["order_information_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool order_information_visible {
            get {
                return ((bool)(this["order_information_visible"]));
            }
            set {
                this["order_information_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string card_information_label {
            get {
                return ((string)(this["card_information_label"]));
            }
            set {
                this["card_information_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool card_information_visible {
            get {
                return ((bool)(this["card_information_visible"]));
            }
            set {
                this["card_information_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string customer_information_label {
            get {
                return ((string)(this["customer_information_label"]));
            }
            set {
                this["customer_information_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool customer_information_visible {
            get {
                return ((bool)(this["customer_information_visible"]));
            }
            set {
                this["customer_information_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bill_middle_name_label {
            get {
                return ((string)(this["bill_middle_name_label"]));
            }
            set {
                this["bill_middle_name_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_middle_name_visible {
            get {
                return ((bool)(this["bill_middle_name_visible"]));
            }
            set {
                this["bill_middle_name_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_middle_name_edit {
            get {
                return ((bool)(this["bill_middle_name_edit"]));
            }
            set {
                this["bill_middle_name_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_middle_name_mandatory {
            get {
                return ((bool)(this["bill_middle_name_mandatory"]));
            }
            set {
                this["bill_middle_name_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bill_last_name_label {
            get {
                return ((string)(this["bill_last_name_label"]));
            }
            set {
                this["bill_last_name_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_last_name_visible {
            get {
                return ((bool)(this["bill_last_name_visible"]));
            }
            set {
                this["bill_last_name_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_last_name_mandatory {
            get {
                return ((bool)(this["bill_last_name_mandatory"]));
            }
            set {
                this["bill_last_name_mandatory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bill_last_name_edit {
            get {
                return ((bool)(this["bill_last_name_edit"]));
            }
            set {
                this["bill_last_name_edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string font_family {
            get {
                return ((string)(this["font_family"]));
            }
            set {
                this["font_family"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string font_size {
            get {
                return ((string)(this["font_size"]));
            }
            set {
                this["font_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string color {
            get {
                return ((string)(this["color"]));
            }
            set {
                this["color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string background_color {
            get {
                return ((string)(this["background_color"]));
            }
            set {
                this["background_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_color {
            get {
                return ((string)(this["btn_color"]));
            }
            set {
                this["btn_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_background_color {
            get {
                return ((string)(this["btn_background_color"]));
            }
            set {
                this["btn_background_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_height {
            get {
                return ((string)(this["btn_height"]));
            }
            set {
                this["btn_height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_width {
            get {
                return ((string)(this["btn_width"]));
            }
            set {
                this["btn_width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_border_top_left_radius {
            get {
                return ((string)(this["btn_border_top_left_radius"]));
            }
            set {
                this["btn_border_top_left_radius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_border_top_right_radius {
            get {
                return ((string)(this["btn_border_top_right_radius"]));
            }
            set {
                this["btn_border_top_right_radius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_border_bottom_left_radius {
            get {
                return ((string)(this["btn_border_bottom_left_radius"]));
            }
            set {
                this["btn_border_bottom_left_radius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_border_bottom_right_radius {
            get {
                return ((string)(this["btn_border_bottom_right_radius"]));
            }
            set {
                this["btn_border_bottom_right_radius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_border_color {
            get {
                return ((string)(this["btn_border_color"]));
            }
            set {
                this["btn_border_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_border_width {
            get {
                return ((string)(this["btn_border_width"]));
            }
            set {
                this["btn_border_width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_font_size {
            get {
                return ((string)(this["btn_font_size"]));
            }
            set {
                this["btn_font_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24px")]
        public string section_header_font_size {
            get {
                return ((string)(this["section_header_font_size"]));
            }
            set {
                this["section_header_font_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1px")]
        public string line_spacing_size {
            get {
                return ((string)(this["line_spacing_size"]));
            }
            set {
                this["line_spacing_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20px")]
        public string input_field_height {
            get {
                return ((string)(this["input_field_height"]));
            }
            set {
                this["input_field_height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string btn_border_style {
            get {
                return ((string)(this["btn_border_style"]));
            }
            set {
                this["btn_border_style"] = value;
            }
        }
    }
}
